package lab7.part1;

import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author xTCry
 */
public class IntlFrame_Manufacturers extends javax.swing.JInternalFrame {

		public IntlFrame_Manufacturers() {
		initComponents();
	}

	private void updateTable() {
		try {
			table_Manufacturers.setModel(SqlUtils.buildTableModel("SELECT * FROM Manufacturer ORDER BY id"));
		}
		catch (SQLException ex) {
			Logger.getLogger(IntlFrame_Products.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ShowAllMans = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Manufacturers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        edit_Man_Id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edit_Man_Name = new javax.swing.JTextField();
        btn_AddMan = new javax.swing.JButton();
        btn_DeleteMan = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Производители");
        setToolTipText("");

        btn_ShowAllMans.setText("Показать");
        btn_ShowAllMans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShowAllMansActionPerformed(evt);
            }
        });

        table_Manufacturers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_Manufacturers);

        jLabel1.setText("Id");

        jLabel2.setText("Название");

        btn_AddMan.setText("Добавить");
        btn_AddMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddManActionPerformed(evt);
            }
        });

        btn_DeleteMan.setText("Удалить");
        btn_DeleteMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteManActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_ShowAllMans)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(edit_Man_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                            .addComponent(edit_Man_Name))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_AddMan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_DeleteMan)
                        .addGap(66, 235, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edit_Man_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edit_Man_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AddMan)
                    .addComponent(btn_DeleteMan))
                .addGap(8, 8, 8)
                .addComponent(btn_ShowAllMans)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ShowAllMansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShowAllMansActionPerformed
		updateTable();
    }//GEN-LAST:event_btn_ShowAllMansActionPerformed

    private void btn_AddManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddManActionPerformed
		try {
			String manName = edit_Man_Name.getText();
			// if man not exists
			if (!SqlUtils.isExists("SELECT 1 FROM Manufacturer WHERE name='%s'".formatted(manName))) {
				// add man
				SqlUtils.execute("INSERT INTO Manufacturer (name) VALUES ('%s')".formatted(manName));
				updateTable();
			}
			// show error
			else {
				MyUtils.showErrorMessage(this, "Такой производитель уже существует");
			}
		}
		catch (SQLException ex) {
			Logger.getLogger(IntlFrame_Manufacturers.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btn_AddManActionPerformed

    private void btn_DeleteManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteManActionPerformed
		try {
			String teamId = edit_Man_Id.getText();
			// if man exists
			if (!teamId.equals("") && SqlUtils.isExists("SELECT 1 FROM Manufacturer WHERE id=%s".formatted(teamId))) {
				// если к производителю НЕ привязяны продукты
				if (!SqlUtils.isExists("SELECT 1 FROM Product WHERE man_id=%s".formatted(teamId))) {
					// delete man
					SqlUtils.execute("DELETE FROM Manufacturer WHERE id=%s".formatted(teamId));
					updateTable();
				}
				// error (к производителю привязаны продукты)
				else {
					MyUtils.showErrorMessage(this, "К производителю привязаны продукты");
				}
			}
			// show error
			else {
				MyUtils.showErrorMessage(this, "Такой производитель не существует");
			}
		}
		catch (SQLException ex) {
			Logger.getLogger(IntlFrame_Manufacturers.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btn_DeleteManActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddMan;
    private javax.swing.JButton btn_DeleteMan;
    private javax.swing.JButton btn_ShowAllMans;
    private javax.swing.JTextField edit_Man_Id;
    private javax.swing.JTextField edit_Man_Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Manufacturers;
    // End of variables declaration//GEN-END:variables
}
