package lab7.part1;

import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author xTCry
 */
public class IntlFrame_Report extends javax.swing.JInternalFrame {

		public IntlFrame_Report() {
		initComponents();
	}

	private void updateTable() {
		try {
			String query = "SELECT p.id AS product_id, p.name AS product, m.name AS manufacturer, m.id AS manufacturer_id "
				+ "FROM   product AS p "
				+ "JOIN manufacturer AS m ON m.id = p.man_id "
				+ "ORDER  BY p.id";
			
			// names of columns
			Vector<String> columnNames = new Vector<>();
			int columnCount = table.getColumnCount();
			for (int column = 0; column < columnCount; column++) {
				columnNames.add(table.getColumnName(column));
			}
		
			table.setModel(SqlUtils.buildTableModel(query, columnNames));
		}
		catch (SQLException ex) {
			Logger.getLogger(IntlFrame_Report.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ShowAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btn_PrintTable = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Отчет");

        btn_ShowAll.setText("Показать");
        btn_ShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShowAllActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product", "Manufacturer", "Manufacturer Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        btn_PrintTable.setText("Печать");
        btn_PrintTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrintTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_ShowAll)
                .addGap(18, 18, 18)
                .addComponent(btn_PrintTable)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ShowAll)
                    .addComponent(btn_PrintTable))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShowAllActionPerformed
		updateTable();
    }//GEN-LAST:event_btn_ShowAllActionPerformed

    private void btn_PrintTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrintTableActionPerformed
        try {
			if (table.getColumnCount() > 0) {
				table.print(JTable.PrintMode.FIT_WIDTH, new MessageFormat("Products"), null);
			}
		}
		catch (PrinterException pe) {
			pe.printStackTrace();
		}
    }//GEN-LAST:event_btn_PrintTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_PrintTable;
    private javax.swing.JButton btn_ShowAll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
