package lab7.part1;

import javax.swing.WindowConstants;

public class MainFrame extends javax.swing.JFrame {
	
	public MainFrame() {
		initComponents();
		
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		
		SqlUtils.init();
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        men_File = new javax.swing.JMenu();
        menu_File_Report = new javax.swing.JMenuItem();
        menu_File_Exit = new javax.swing.JMenuItem();
        menu_Tables = new javax.swing.JMenu();
        menu_Tables_Manufacturers = new javax.swing.JMenuItem();
        menu_Tables_Products = new javax.swing.JMenuItem();
        menu_About = new javax.swing.JMenu();
        menu_About_Show = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        men_File.setText("Файл");

        menu_File_Report.setText("Отчет...");
        menu_File_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_File_ReportActionPerformed(evt);
            }
        });
        men_File.add(menu_File_Report);

        menu_File_Exit.setText("Выйти");
        menu_File_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_File_ExitActionPerformed(evt);
            }
        });
        men_File.add(menu_File_Exit);

        jMenuBar1.add(men_File);

        menu_Tables.setText("Таблицы");

        menu_Tables_Manufacturers.setText("Производители");
        menu_Tables_Manufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Tables_ManufacturersActionPerformed(evt);
            }
        });
        menu_Tables.add(menu_Tables_Manufacturers);

        menu_Tables_Products.setText("Продукты");
        menu_Tables_Products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Tables_ProductsActionPerformed(evt);
            }
        });
        menu_Tables.add(menu_Tables_Products);

        jMenuBar1.add(menu_Tables);

        menu_About.setText("Справка");

        menu_About_Show.setText("Показать");
        menu_About_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_About_ShowActionPerformed(evt);
            }
        });
        menu_About.add(menu_About_Show);

        jMenuBar1.add(menu_About);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_File_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_File_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menu_File_ExitActionPerformed

    private void menu_Tables_ManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Tables_ManufacturersActionPerformed
        IntlFrame_Manufacturers fr = new IntlFrame_Manufacturers();
		Desktop.add(fr);
		fr.setVisible(true);
    }//GEN-LAST:event_menu_Tables_ManufacturersActionPerformed

    private void menu_Tables_ProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Tables_ProductsActionPerformed
        IntlFrame_Products fr = new IntlFrame_Products();
		Desktop.add(fr);
		fr.setVisible(true);
    }//GEN-LAST:event_menu_Tables_ProductsActionPerformed

    private void menu_About_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_About_ShowActionPerformed
        IntlFrame_About fr = new IntlFrame_About();
		Desktop.add(fr);
		fr.setVisible(true);
    }//GEN-LAST:event_menu_About_ShowActionPerformed

    private void menu_File_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_File_ReportActionPerformed
        IntlFrame_Report fr = new IntlFrame_Report();
		Desktop.add(fr);
		fr.setVisible(true);
    }//GEN-LAST:event_menu_File_ReportActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu men_File;
    private javax.swing.JMenu menu_About;
    private javax.swing.JMenuItem menu_About_Show;
    private javax.swing.JMenuItem menu_File_Exit;
    private javax.swing.JMenuItem menu_File_Report;
    private javax.swing.JMenu menu_Tables;
    private javax.swing.JMenuItem menu_Tables_Manufacturers;
    private javax.swing.JMenuItem menu_Tables_Products;
    // End of variables declaration//GEN-END:variables
}
