/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2.p2.ui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class Lab2UI_ extends javax.swing.JFrame {

	SQL sql;
	final static String
		ACTION_SHOW_TEAMS = "Показать команды",
		ACTION_ADD_TEAM = "Добавить команду",
		ACTION_DELETE_TEAM = "Удалить команду",
		ACTION_SHOW_PLAYERS = "Показать игроков",
		ACTION_FILTER_PLAYERS_BY_TEAM = "Фильтр игроков по команде",
		ACTION_ADD_PLAYER = "Добавить игрока",
		ACTION_DELETE_PLAYER = "Удалить игрока";

	public Lab2UI_() throws Exception {
		String db = "football", user = "le", password = "ledb",
			url = String.format(
				"jdbc:sqlserver://localhost;database=%s;user=%s;password=%s",
				db, user, password);
		sql = new SQL(url);

		initComponents();
		//----------------------
		switchPlayerElements(false);

		ArrayList<String> lst = new ArrayList<>(
			Arrays.asList(
				ACTION_SHOW_TEAMS,
				ACTION_SHOW_PLAYERS,
				ACTION_FILTER_PLAYERS_BY_TEAM,
				ACTION_ADD_TEAM,
				ACTION_ADD_PLAYER,
				ACTION_DELETE_TEAM,
				ACTION_DELETE_PLAYER
			));

		DefaultComboBoxModel dml = new DefaultComboBoxModel();
		for (int i = 0; i < lst.size(); i++) {
			dml.addElement(lst.get(i));
		}
		cmbox_Action.setModel(dml);
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		cmbox_Action = new javax.swing.JComboBox<>();
		lbl_Team = new javax.swing.JLabel();
		lbl_TeamName = new javax.swing.JLabel();
		lbl_PlayerName3 = new javax.swing.JLabel();
		lbl_Player = new javax.swing.JLabel();
		lbl_PlayerName2 = new javax.swing.JLabel();
		lbl_PlayerName1 = new javax.swing.JLabel();
		tbox_TeamName = new javax.swing.JTextField();
		tbox_PlayerName1 = new javax.swing.JTextField();
		tbox_PlayerName2 = new javax.swing.JTextField();
		tbox_PlayerName3 = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();
		btn_DoAction = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Действие");

		cmbox_Action.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cmbox_Action_ActionPerformed(evt);
			}
		});

		lbl_Team.setText("Команда");

		lbl_TeamName.setText("Название");

		lbl_PlayerName3.setText("Отчество");

		lbl_Player.setText("Игрок");

		lbl_PlayerName2.setText("Фамилия");

		lbl_PlayerName1.setText("Имя");

		table.setModel(new javax.swing.table.DefaultTableModel(
			new Object [][] {

			},
			new String [] {

			}
		));
		jScrollPane1.setViewportView(table);

		btn_DoAction.setText("Выполнить");
		btn_DoAction.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btn_DoAction_ActionPerformed(evt);
				} catch (SQLException throwables) {
					throwables.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(lbl_PlayerName3)
							.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1)
								.addComponent(lbl_TeamName)
								.addComponent(lbl_PlayerName1)
								.addComponent(lbl_PlayerName2))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(lbl_Team)
								.addComponent(lbl_Player)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
									.addComponent(tbox_PlayerName3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
									.addComponent(tbox_PlayerName2, javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(tbox_PlayerName1, javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(tbox_TeamName, javax.swing.GroupLayout.Alignment.LEADING))
								.addComponent(cmbox_Action, 0, 214, Short.MAX_VALUE)))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
							.addGap(0, 0, Short.MAX_VALUE)
							.addComponent(btn_DoAction)))
					.addGap(12, 12, 12)
					.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1)
								.addComponent(cmbox_Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(btn_DoAction)
							.addGap(9, 9, 9)
							.addComponent(lbl_Team)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_TeamName)
								.addComponent(tbox_TeamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addGap(18, 18, 18)
							.addComponent(lbl_Player)
							.addGap(4, 4, 4)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_PlayerName1)
								.addComponent(tbox_PlayerName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tbox_PlayerName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lbl_PlayerName2))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tbox_PlayerName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lbl_PlayerName3))
							.addContainerGap(67, Short.MAX_VALUE))))
		);

		pack();
	}// </editor-fold>

	private void switchPlayerElements(boolean val) {
		lbl_Player.setEnabled(val);
		lbl_PlayerName1.setEnabled(val);
		lbl_PlayerName2.setEnabled(val);
		lbl_PlayerName3.setEnabled(val);
		tbox_PlayerName1.setEnabled(val);
		tbox_PlayerName2.setEnabled(val);
		tbox_PlayerName3.setEnabled(val);
	}

	private void btn_DoAction_ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
		switch (Objects.requireNonNull(cmbox_Action.getSelectedItem()).toString()) {
			case ACTION_SHOW_TEAMS -> {
				table.setModel(sql.buildTableModel("SELECT * FROM Team"));
			}
			case ACTION_SHOW_PLAYERS -> {
				table.setModel(sql.buildTableModel("SELECT * FROM Player"));
			}
			case ACTION_FILTER_PLAYERS_BY_TEAM -> {
				String teamName = tbox_TeamName.getText();
				table.setModel(sql.buildTableModel(String.format(
					"SELECT * FROM player WHERE TeamID = (SELECT ID FROM Team WHERE TeamName = '%s');",
					teamName
				)));
			}
			case ACTION_ADD_TEAM -> {
				String teamName = tbox_TeamName.getText();
				if (sql.exists(String.format(
					"SELECT 1 FROM Team WHERE TeamName = '%s';",
					teamName
				))) {
					showErrorDialog("Ошибка: команда уже существует");
					return;
				}
				sql.execute(String.format(
					"INSERT INTO Team (TeamName) VALUES ('%s');",
					teamName
				));
				showInfoDialog("Команда добавлена");
			}
			case ACTION_ADD_PLAYER -> {
				String pName1 = tbox_PlayerName1.getText(),
					pName2 = tbox_PlayerName2.getText(),
					pName3 = tbox_PlayerName3.getText(),
					teamName = tbox_TeamName.getText();
				var rs = sql.getResultSet(String.format(
					"SELECT ID FROM Team WHERE TeamName = '%s'",
					teamName
				));
				String teamId;
				if (!rs.next()) {
					showErrorDialog("Ошибка: такая команда не существует");
					return;
				}
				teamId = rs.getString(1);

				if (sql.exists(String.format(
					"SELECT 1 FROM Player WHERE TeamID=%s AND PlayerName='%s' AND PlayerSurname='%s' AND PlayerPatronymic='%s';",
					teamId, pName1, pName2, pName3
				))) {
					showErrorDialog("Ошибка: такой игрок уже существует");
					return;
				}
				sql.execute(String.format(
					"INSERT INTO Player (PlayerName, PlayerSurname, PlayerPatronymic, TeamID) VALUES ('%s', '%s', '%s', %s);",
					pName1, pName2, pName3, teamId
				));
				showInfoDialog("Игрок добавлен");
			}
			case ACTION_DELETE_TEAM -> {
				String teamName = tbox_TeamName.getText();
				if (!sql.exists(String.format("SELECT 1 FROM Team WHERE TeamName = '%s';", teamName))) {
					showErrorDialog("Ошибка: такой команды не существует");
					return;
				}
				sql.execute(String.format("DELETE FROM Team WHERE TeamName = '%s';", teamName));
				showInfoDialog("Команда удалена");
			}
			case ACTION_DELETE_PLAYER -> {
				String pName1 = tbox_PlayerName1.getText(),
					pName2 = tbox_PlayerName2.getText(),
					pName3 = tbox_PlayerName3.getText(),
					teamName = tbox_TeamName.getText();
				var rs = sql.getResultSet(String.format(
					"SELECT ID FROM Team WHERE TeamName = '%s'",
					teamName
				));
				String teamId;
				if (!rs.next()) {
					showErrorDialog("Ошибка: такой команды не существует");
					return;
				}
				teamId = rs.getString(1);
				if (!sql.exists(String.format(
					"SELECT 1 FROM Player WHERE TeamID=%s AND PlayerName='%s' AND PlayerSurname='%s' AND PlayerPatronymic='%s';",
					teamId, pName1, pName2, pName3
				))) {
					showErrorDialog("Ошибка: в указанной команде нет такого игрока");
					return;
				}
				sql.execute(String.format(
					"DELETE FROM Player WHERE TeamID=%s AND PlayerName='%s' AND PlayerSurname='%s' AND PlayerPatronymic='%s';",
					teamId, pName1, pName2, pName3
				));
				showInfoDialog("Игрок удален");
			}
		}
	}

	private void showInfoDialog(String msg) {
		JOptionPane.showMessageDialog(null, msg, "", JOptionPane.INFORMATION_MESSAGE);
	}

	private void showErrorDialog(String msg) {
		JOptionPane.showMessageDialog(null, msg, "", JOptionPane.ERROR_MESSAGE);
	}

	private void cmbox_Action_ActionPerformed(java.awt.event.ActionEvent evt) {
		switch (cmbox_Action.getSelectedItem().toString()) {
			case ACTION_ADD_PLAYER, ACTION_DELETE_PLAYER -> switchPlayerElements(true);
			default -> switchPlayerElements(false);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Lab2UI_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Lab2UI_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Lab2UI_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Lab2UI_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				try {
					new Lab2UI_().setVisible(true);
				} catch (Exception ex) {
					Logger.getLogger(Lab2UI_.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btn_DoAction;
	private javax.swing.JComboBox<String> cmbox_Action;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel lbl_Team;
	private javax.swing.JLabel lbl_TeamName;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lbl_Player;
	private javax.swing.JLabel lbl_PlayerName1;
	private javax.swing.JLabel lbl_PlayerName2;
	private javax.swing.JLabel lbl_PlayerName3;
	private javax.swing.JTable table;
	private javax.swing.JTextField tbox_PlayerName1;
	private javax.swing.JTextField tbox_PlayerName2;
	private javax.swing.JTextField tbox_PlayerName3;
	private javax.swing.JTextField tbox_TeamName;
	// End of variables declaration
}
